# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGPPOsUV8NYjDWOHX-65D8LRhHgoJJ_5

Step 1 – Load & Inspect Dataset
"""

import pandas as pd

df = pd.read_csv("/content/emails.csv")
print(df.head())

"""Step 2 – Define Features (X) & Labels (y)"""

X = df.drop(columns=["Prediction", "Email No."])  # features
y = df["Prediction"]  # target

"""✅ Step 3 – Train/Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="constant", fill_value=0)
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

print(y.isnull().sum())
print(df[df["Prediction"].isnull()].head())

# Drop rows where Prediction is NaN
df = df.dropna(subset=["Prediction"])

# Reset index (optional, for cleanliness)
df = df.reset_index(drop=True)

"""Step 4 – Train Logistic Regression"""

X = df.drop(columns=["Prediction", "Email No."])
y = df["Prediction"]

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Handle feature NaNs (fill with 0)
imputer = SimpleImputer(strategy="constant", fill_value=0)
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))