# -*- coding: utf-8 -*-
"""Assi 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AtBM8DmjDEfkQeQ49VDjrUz-dVKSgp3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression


df = pd.read_csv("/content/minihomeprices.csv")
df["bedrooms"].fillna(df["bedrooms"].mean(), inplace=True)

print(df)

"""Step 2 – Separate features (X) and target (y)"""

X = df[["area", "bedrooms", "age"]].values
y = df["price"].values.reshape(-1, 1)

"""Step 3 – Scale features (important for gradient descent)"""

mu = X.mean(axis=0)
sigma = X.std(axis=0)

X_scaled = (X - mu) / sigma
Xb = np.c_[np.ones((X_scaled.shape[0], 1)), X_scaled]

"""🟢 Step 4 – Implement Gradient Descent (from scratch"""

def gradient_descent(Xb, y, alpha=0.05, iterations=500):
    m, n = Xb.shape
    theta = np.zeros((n, 1))
    costs = []

    for i in range(iterations):
        y_hat = Xb @ theta
        error = y_hat - y
        grad = (Xb.T @ error) / m
        theta -= alpha * grad
        cost = (error.T @ error) / (2*m)
        costs.append(float(cost))
    return theta, costs

theta, costs = gradient_descent(Xb, y, alpha=0.01, iterations=1000)
print("Learned parameters (theta):\n", theta)

"""🟢 Step 5 – Plot Cost Function Convergence"""

plt.plot(costs)
plt.xlabel("Iterations")
plt.ylabel("Cost (MSE)")
plt.title("Cost Function Convergence")
plt.show()

"""🟢 Step 6 – Predictions (from scratch)"""

y_pred_scratch = Xb @ theta

mae_s = mean_absolute_error(y, y_pred_scratch)
rmse_s = np.sqrt(mean_squared_error(y, y_pred_scratch))
r2_s = r2_score(y, y_pred_scratch)

print(f"From-Scratch Model -> MAE: {mae_s:.2f}, RMSE: {rmse_s:.2f}, R²: {r2_s:.4f}")

"""🟢 Step 7 – Compare with Sklearn LinearRegression"""

lr = LinearRegression()
lr.fit(X, y)
y_pred_sklearn = lr.predict(X)

mae_k = mean_absolute_error(y, y_pred_sklearn)
rmse_k = np.sqrt(mean_squared_error(y, y_pred_sklearn))
r2_k = r2_score(y, y_pred_sklearn)

print("Sklearn intercept:", lr.intercept_)
print("Sklearn coefficients:", lr.coef_)

print(f"Sklearn Model -> MAE: {mae_k:.2f}, RMSE: {rmse_k:.2f}, R²: {r2_k:.4f}")